version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: botcalm_mongo
    environment:
      MONGO_INITDB_DATABASE: botcalm
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - botcalm-network

  backend:
    build:
      context: ./botcalm-be-app
      dockerfile: Dockerfile
    container_name: botcalm_backend
    env_file:
      - ./botcalm-be-app/.env
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - botcalm-network

  frontend:
    build:
      context: ./botcalm-fe-app
      dockerfile: Dockerfile
    container_name: botcalm_frontend
    env_file:
      - ./botcalm-fe-app/.env
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - botcalm-network

networks:
  botcalm-network:
    driver: bridge

volumes:
  mongodb_data:
